# Generated by Django 2.2.3 on 2019-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='resource',
            field=models.FileField(upload_to='None/', verbose_name='Learning Resouce'),
        ),
    ]
